import { generatePersonalizedMessage, quickPersonalize } from '@/lib/ai/personalize';
import { auth } from '@/lib/auth';
import { leadDoc, messagesCollection, serverTimestamp, stripUndefined } from '@/lib/firebase/collections';
import { NextRequest, NextResponse } from 'next/server';
import { z } from 'zod';

// Validation schema
const generateMessageSchema = z.object({
  leadId: z.string().min(1, 'Lead ID is required'),
  type: z.enum(['EMAIL']).optional().default('EMAIL'),
  useAI: z.boolean().default(true),
  saveMessage: z.boolean().default(true),
});

// POST /api/ai/generate - Generate a personalized message for a lead
export async function POST(request: NextRequest) {
  try {
    const session = await auth();
    if (!session?.user) {
      return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });
    }

    if (session.user.role === 'VIEWER') {
      return NextResponse.json(
        { error: 'Insufficient permissions' },
        { status: 403 }
      );
    }

    const teamId = session.user.teamId;

    const body = await request.json();
    const { leadId, useAI, saveMessage } = generateMessageSchema.parse(body);

    // Get the lead
    const leadDocRef = leadDoc(teamId, leadId);
    const leadSnap = await leadDocRef.get();

    if (!leadSnap.exists) {
      return NextResponse.json({ error: 'Lead not found' }, { status: 404 });
    }

    const lead = {
      id: leadSnap.id,
      ...leadSnap.data(),
    } as any;

    let content: string;
    let subject: string | undefined;
    let provider: string = 'template';
    let model: string = 'none';
    let generatedBy: 'ai' | 'template' = 'template';
    let dataUsed: any = null;

    console.log(`📝 [Message Generation] Lead: ${lead.businessName} | Type: EMAIL | UseAI: ${useAI}`);

    if (useAI) {
      try {
        console.log(`🤖 [AI] Attempting AI generation for ${lead.businessName}...`);
        const result = await generatePersonalizedMessage({
          teamId,
          lead,
        });
        content = result.content;
        subject = result.subject;
        provider = result.provider;
        model = result.model;
        dataUsed = result.dataUsed;
        generatedBy = 'ai';
        console.log(`✅ [AI] Successfully generated with ${provider}/${model}`);
      } catch (aiError) {
        console.error(`❌ [AI] Generation failed, falling back to template:`, aiError);
        content = quickPersonalize(lead);
        generatedBy = 'template';
        console.log(`📋 [Template] Using template fallback for ${lead.businessName}`);
      }
    } else {
      content = quickPersonalize(lead);
      generatedBy = 'template';
      console.log(`📋 [Template] Using template (AI disabled) for ${lead.businessName}`);
    }

    // Optionally save the message
    let message = null;
    if (saveMessage) {
      const messageData = stripUndefined({
        teamId,
        leadId,
        type: 'EMAIL',
        subject: subject ?? null,
        content,
        status: 'DRAFT',
        generatedBy,
        aiProvider: generatedBy === 'ai' ? provider : null,
        aiModel: generatedBy === 'ai' ? model : null,
        dataUsed: dataUsed ?? null,
        createdAt: serverTimestamp(),
        updatedAt: serverTimestamp(),
      });

      const messageDocRef = messagesCollection(teamId).doc();
      await messageDocRef.set(messageData);

      message = {
        id: messageDocRef.id,
        ...messageData,
        lead,
      };

      console.log(`💾 [Message] Saved message ID: ${message.id} | Generated by: ${generatedBy}`);

      // Update lead status to MESSAGE_READY if still NEW or QUALIFIED
      if (lead.status === 'NEW' || lead.status === 'QUALIFIED') {
        await leadDocRef.update({
          status: 'MESSAGE_READY',
          updatedAt: serverTimestamp(),
        });
      }
    }

    return NextResponse.json({
      success: true,
      content,
      subject,
      provider,
      model,
      generatedBy,
      dataUsed,
      message,
    });
  } catch (error) {
    if (error instanceof z.ZodError) {
      return NextResponse.json(
        { error: 'Validation failed', details: error.errors },
        { status: 400 }
      );
    }
    console.error('Error generating message:', error);
    return NextResponse.json(
      { error: 'Failed to generate message' },
      { status: 500 }
    );
  }
}
